//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAddressBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public byte[] EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public byte[] Office { get; set; }
    }
}
